Web_Module/NOlx/Models/House.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NOlx.Models
{
    public class House
    {
        [Key]
        public int HouseId { get; set; }


        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        public string Title { get; set; }
        public string Description { get; set; }

        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        public int OverallQual  { get; set; }

        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(1, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        public float Price { get; set; }

        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(1, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        
        public float SuggestedPrice { get; set; }
        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        public int MSSubClass { get; set; }
        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(0, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        public int FullBath { get; set; }
        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(1, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        public int TotRmsAbvGrd { get; set; }

        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(1, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        public int YearBuilt { get; set; }

        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(1, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        public float GrLivArea { get; set; }
        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        [Range(0, Int64.MaxValue, ErrorMessage = "Acest camp este obligatoriu")]
        public int KitchenQual { get; set; }
        public byte[] Image { get; set; }
        [Required(ErrorMessage = "Acest camp este obligatoriu")]
        public int GarageCars { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

    }


}

Web_Module/NOlx/Controllers/HouseController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using NOlx.Models;
using NOlx.Models.DTOModels;
using NOlx.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Web.Script.Serialization;

namespace NOlx.Controllers
{
    public class HouseController : Controller
    {
        private ApplicationDbContext db = ApplicationDbContext.Create();
        private readonly IHouseService _houseService;
        public HouseController()
        {
            _houseService = new HouseService();
        }
        private string defaultImagePath = "../Content/Images/Default.png";
        // GET: House
        public ActionResult Index(SearchFilter searchFilter)
        {
            var  houses = db.Houses.Include("User");
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            ViewBag.Houses = _houseService.GetHousesByFilters(searchFilter);
            ViewBag.SearchFilters = searchFilter;
            return View();
        }

        public void GetHouses(SearchFilter searchFilter)
        {
            ViewBag.Houses = _houseService.GetHousesByFilters(searchFilter);
        }

        public ActionResult Show(int id) 
        {
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        public ActionResult MyHouses()
        {
            // daca nu este autentificat
            if (!User.Identity.IsAuthenticated)
            {   
                // redirect catre pagina de locare
                return RedirectToAction("Login", "Account");
            }

            var UserId = User.Identity.GetUserId();

            var houses = db.Houses.Include("User").Where(x => x.UserId == UserId);
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            // var houses2 = from house in houses select house;
            ViewBag.Houses = houses;

            return View();
        }

        public ActionResult New()
        {
            // daca nu este autentificat
            if (!User.Identity.IsAuthenticated)
            {   
                // redirect catre pagina de locare
                return RedirectToAction("Login", "Account");
            }
            else 
            {
                House house = new House();
                house.UserId = User.Identity.GetUserId();
                return View(house);
            }
        }
     

        [HttpPost]
        public ActionResult New(House house, HttpPostedFileBase image1)
        {
            try
            {
                if (ModelState.IsValid)
                {   
                    if(image1 !=null)
                    {
                        house.Image = new byte[image1.ContentLength];
                        image1.InputStream.Read(house.Image, 0, image1.ContentLength);    
                    }
                    else 
                    {
                        house.Image = System.IO.File.ReadAllBytes(System.Web.HttpContext.Current.Server.MapPath(defaultImagePath));
                    }
                    
                    db.Houses.Add(house);
                    db.SaveChanges();
                    TempData["message"] = TempData["message"] + "Anuntul a fost adaugat!";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(house);
                }
            }
            catch (Exception e)
            {
                return View(house);
            }
        }
       
        public ActionResult Edit(int id)
        {
            House house = db.Houses.Find(id);
            ViewBag.House = house;
            if (house.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
            {
                return View(house);
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui anunt care nu va apartine!";
                return RedirectToAction("Index");
            }
        }

        [HttpPut]
        public ActionResult Edit(int id, House requestHouse)
        {
            try
            {
                House house= db.Houses.Find(id);
                    if (ModelState.IsValid)
                    {
                        if (TryUpdateModel(house))
                           {
                     
                            house.Title = requestHouse.Title;
                            house.Description = requestHouse.Description;
                            house.Address = requestHouse.Address;
                            house.OverallQual = requestHouse.OverallQual;
                            house.Price = requestHouse.Price;
                            house.SuggestedPrice = requestHouse.SuggestedPrice;
                            house.SuggestedPrice = requestHouse.SuggestedPrice;
                            house.MSSubClass = requestHouse.MSSubClass;
                            house.FullBath = requestHouse.FullBath;
                            house.TotRmsAbvGrd = requestHouse.TotRmsAbvGrd;
                            house.YearBuilt = requestHouse.YearBuilt;
                            house.GrLivArea = requestHouse.GrLivArea;
                            house.KitchenQual = requestHouse.KitchenQual;
                            house.GarageCars = requestHouse.GarageCars;
                            db.SaveChanges();     
                        }
                    }
                    else
                    {
                    return View(house);
                    }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            House house = db.Houses.Find(id);
            if (house.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
            {
                db.Houses.Remove(house);
                db.SaveChanges();
            }
            else
            {
                TempData["message"] = "Nu aveti dreptul sa stergeti un anunt care nu va apartine!";
                return RedirectToAction("Index");
            }
            return RedirectToAction("MyHouses");
        }

     

        
        // nu o sa mearga pe calculatorul vostru ( cai absolute si dependinte de pachete python )
        // [HttpPost]
        // public JsonResult GetPredictedPrice(House house)
        // {
        //     string result;
        //     string errors;
        //     string scriptPath = "C:\\PythonWork\\NOlx\\Web_Module\\NOlx\\Controllers\\predict.py";
        //     string arguments = house.OverallQual.ToString() + ' ' + house.MSSubClass.ToString() + ' ' + house.FullBath.ToString() + ' ' 
        //                      + house.TotRmsAbvGrd.ToString() + ' ' + house.YearBuilt.ToString() + ' ' + house.GrLivArea.ToString() + ' ' 
        //                      + house.KitchenQual.ToString() + ' ' + house.GarageCars.ToString();

        //     ProcessStartInfo start = new ProcessStartInfo();
        //     start.FileName = "C:\\Users\\georg\\Anaconda3\\envs\\tensorflow_env\\python.exe";
        //     // var json = new JavaScriptSerializer().Serialize(house);
        //     start.Arguments = scriptPath + " " + arguments;
        //     start.UseShellExecute = false;
        //     start.RedirectStandardOutput = true;
        //     start.CreateNoWindow = true;
        //     start.RedirectStandardError = true;
        //     using (Process process = Process.Start(start))
        //     {
        //         using (StreamReader reader = process.StandardOutput)
        //         {
        //             errors = process.StandardError.ReadToEnd();
        //             result = reader.ReadToEnd();
        //             Console.Write(errors);
        //             Console.Write(result);
        //         }
        //     }
        //     return Json(result);   
        // }

        // functie 'placeholder'
        [HttpPost]
        public JsonResult GetPredictedPrice(House house)
        {
            Random rnd = new Random();
            return Json(rnd.Next(10000, 1500000));
        }

    }
    public static class Utilss
    {
        private static ApplicationDbContext _context = ApplicationDbContext.Create();
        public static string GetUserName(string id)
        {
            return _context.Users.FirstOrDefault(x => x.Id == id).UserName.ToString();
        }
        public static string GetMsSubClass(int id)
        {
            var msSubClasses = new List<SelectListItem>
            {
                new SelectListItem { Text = "Selectati...", Value = "-1" },
                new SelectListItem { Text = "1 etaj - an 1946 sau mai nou", Value = "5" },
                new SelectListItem { Text = "1 etaj - an 1945 sau mai vechi", Value = "6" },
                new SelectListItem { Text = "1 etaj - mansarda finisata - orice an", Value = "7" },
                new SelectListItem { Text = "1-1/2 etaje - nefinisat - orice an", Value = "8" },
                new SelectListItem { Text = "1-1/2 etaje - finisat - orice an", Value = "9" },
                new SelectListItem { Text = "2 etaje - an 1946 sau mai nou", Value = "10" },
                new SelectListItem { Text = "2 etaje - an 1945 sau mai vechi", Value = "11" },
                new SelectListItem { Text = "2-1/2 etaje - orice an", Value = "12" },
                new SelectListItem { Text = "MULTILEVEL", Value = "13" },
                new SelectListItem { Text = "Foaier impartit", Value = "15" },

Web_Module/NOlx/Views/House/Index.cshtml
@model NOlx.Models.House
@{
    ViewBag.Title = "Anunturi disponibile";
}
@using NOlx.Controllers
<div style="text-align: center; width: 100%">
    <br />
    <h2>@ViewBag.Title</h2>
    <br />
</div>

<div class="col-sm-12">

    <div class="col-sm-4">
        

    

    @using (Html.BeginForm("Index", "House", FormMethod.Get, new { ViewBag.SearchFilters }))
    {
        <input type="text" placeholder="Cauta dupa numele anuntului..." class="form-control form-group" name="ByTitle"

        <label><b>Pret: </b></label>
        <input type="number" placeholder="Pret minim" class="form-control form-group" value="PriceMin" name="PriceMin" />
        <input type="number" placeholder="Pret maxim" class="form-control form-group" value="PriceMax" name="PriceMax" />
        <br />


        <label>An de constructie: </label>
        <input type="number" placeholder="Din anul..." class="form-control form-group" value="YearBuiltMin" name="YearBuiltMin" />
        <input type="number" placeholder="Pana in anul..." class="form-control form-group" value="YearBuiltMax" name="YearBuiltMax" />
        <br />


        <label>Locuri de parcare: </label>
        <input type="number" placeholder="Minim nr locuri..." class="form-control form-group" value="GarageCarsMin" name="GarageCarsMin" />
        <input type="number" placeholder="Maxim nr locuri..." class="form-control form-group" value="GarageCarsMax" name="GarageCarsMax" />
        <br />

        
        <label>Suprafata locuibila: </label>
        <input type="number" placeholder="Suprafata minima mp" class="form-control form-group" value="GrLivMin" name="GrLivMin" />
        <input type="number" placeholder="Suprafata maxima mp" class="form-control form-group" value="GrLivMax" name="GrLivMax" />
        <br />



        <br />

        <button type="submit" class="btn btn-info">Cauta</button>

    }
</div>

    @*@if (TempData.ContainsKey("message"))
    {
        <h3 class="alert alert-info" role="alert">@ViewBag.message</h3>
    }*@

    <h3>Rezultate @ViewBag.Houses.Count</h3>
    <div class="col-sm-8 panel panel-default">
        @foreach (NOlx.Models.House house in ViewBag.Houses)
        {
            @Html.Partial("HouseInfo", house);
        }

    </div>


</div>

Web_Module/NOlx/Views/House/MyHouses.cshtml
@model NOlx.Models.House
@{
    ViewBag.Title = "Anunturile mele";
}

<div style="text-align: center; width: 100%">
    <br />
    <h2>@ViewBag.Title</h2>
    <br />
</div>


@if (TempData.ContainsKey("message"))
{
    <h3 class="alert alert-info" role="alert">@ViewBag.message</h3>
}


<div class="panel panel-default">
    @foreach (NOlx.Models.House house in ViewBag.Houses)
    {
        @Html.Partial("MyHouseInfo", house);
    }

</div>

Web_Module/NOlx/Views/House/New.cshtml
@model NOlx.Models.House
@using NOlx.Models
@{
    ViewBag.Titlu = "Adaugare anunt";
}
<br />
<div class="row margin-bottom-15">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h2>@ViewBag.Titlu</h2>
    </div>
</div>
<br/>
<br/>
<br/>
    
<!-- Primul block de selectii -->
@using (Html.BeginForm("New", "House", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    <div class="col-md-4">
        @Html.HiddenFor(m => m.UserId)

        @Html.Label("Title", "Titlu:")
        <br />
        @Html.TextBox("Title", null, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
        <br />
        @Html.Label("Description", "Descriere:")
        <br />
        @Html.TextArea("Description", null, new { @class = "form-control" })
        <br />
        @Html.Label("Address", "Adresa casa")
        <br />
        @Html.TextBox("Address", null, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        <br />
        @Html.Label("OverallQual", "Calitatea finisajelor: ")
        <br />
        @Html.DropDownListFor(m => m.OverallQual, new List<SelectListItem>
        {
            new SelectListItem{ Text="Foarte Excelent",   Value = "10" },
            new SelectListItem{ Text="Excelent",          Value = "9" },
            new SelectListItem{ Text="Foarte Bun",        Value = "8" },
            new SelectListItem{ Text="Bun",               Value = "7" },
            new SelectListItem{ Text="Peste medie",        Value = "6" },
            new SelectListItem{ Text="Medie",              Value = "5" },
            new SelectListItem{ Text="Sub medie",          Value = "4" },
            new SelectListItem{ Text="Rezonabil",         Value = "3" },
            new SelectListItem{ Text="Prost",            Value = "2" },
            new SelectListItem{ Text="Foarte Prost",     Value = "1" },
        }, "Selectati", new { @class = "form-control phase-1" })
        @Html.ValidationMessageFor(m => m.OverallQual, "", new { @class = "text-danger" })
        <br />
        @Html.Label("KitchenQual", "Nivel de echipare bucatarii: ")
        <br />
        <td>
            @Html.DropDownListFor(m => m.KitchenQual, new List<SelectListItem>
        {
            new SelectListItem{ Text="Selectati...", Value = "-1", Selected = true },
            new SelectListItem{ Text="Excelent", Value = "4" },
            new SelectListItem{ Text="Bun", Value = "3" },
            new SelectListItem{ Text="Medie", Value = "2" },
            new SelectListItem{ Text="Rezonabil", Value = "1" },
            new SelectListItem{ Text="Prost", Value = "0" }
        }, new { @class = "form-control phase-1" })
        </td>
        @Html.ValidationMessageFor(m => m.KitchenQual, "", new { @class = "text-danger" })

        <br />
        @Html.Label("MSSubClass", "Tipul de locuință implicată în vânzare:")
        <br />
        <td>
            @Html.DropDownListFor(m => m.MSSubClass, new List<SelectListItem>
        {
            new SelectListItem{ Text="Selectati...", Value = "-1" },
            new SelectListItem{ Text="1 etaj - an 1946 sau mai nou", Value = "5" },
            new SelectListItem{ Text="1 etaj - an 1945 sau mai vechi", Value = "6" },
            new SelectListItem{ Text="1 etaj - mansarda finisata - orice an", Value = "7" },
            new SelectListItem{ Text="1-1/2 etaje - nefinisat - orice an", Value = "8" },
            new SelectListItem{ Text="1-1/2 etaje - finisat - orice an", Value = "9" },
            new SelectListItem{ Text="2 etaje - an 1946 sau mai nou", Value = "10" },
            new SelectListItem{ Text="2 etaje - an 1945 sau mai vechi", Value = "11" },
            new SelectListItem{ Text="2-1/2 etaje - orice an", Value = "12" },
            new SelectListItem{ Text="MULTILEVEL", Value = "13" },
            new SelectListItem{ Text="Foaier impartit", Value = "15" },
            new SelectListItem{ Text="Duplex - orice an", Value = "16" },
            new SelectListItem{ Text="1 etaj PUD - an 1946 sau mai nou", Value = "0" },
            new SelectListItem{ Text="1-1/2 etaje PUD - orice varsta", Value = "1" },
            new SelectListItem{ Text="2 etaje PUD - 1946 sau mai nou", Value = "2" },
            new SelectListItem{ Text="PUD - MULTILEVEL", Value = "3" },
            new SelectListItem{ Text="Conversie 2 familii - orice an", Value = "4" },
        }, new { @class = "form-control phase-1" })
        </td>
        @Html.ValidationMessageFor(m => m.MSSubClass, "", new { @class = "text-danger" })
    </div>
    
    <div class="col-md-4">

        @Html.Label("YearBuilt", "Anul constructiei:")
        <br />
        @Html.TextBox("YearBuilt", null, new { @class = "form-control phase-1" })
        @Html.ValidationMessageFor(m => m.YearBuilt, "", new { @class = "text-danger" })
        <br />
        @Html.Label("GrLivArea", "Suprafata de locuit in metri patrati:")
        <br />
        @Html.TextBox("GrLivArea", null, new { @class = "form-control phase-1" })
        @Html.ValidationMessageFor(m => m.GrLivArea, "", new { @class = "text-danger" })
        <br /><br />
        @Html.Label("TotRmsAbvGrd", "Numar camere(nu include bai):")
        <br />
        @Html.TextBox("TotRmsAbvGrd", null, new { @class = "form-control phase-1" })
        @Html.ValidationMessageFor(m => m.TotRmsAbvGrd, "", new { @class = "text-danger" })
        <br />
        @Html.Label("FullBath", "Numarul de bai:")
        <br />
        @Html.TextBox("FullBath", null, new { @class = "form-control phase-1" })
        @Html.ValidationMessageFor(m => m.FullBath, "", new { @class = "text-danger" })

        <br />
        @Html.Label("GarageCars", "Capacitate garaj(masurata in numarul de masini):")
        <br />
        @Html.TextBox("GarageCars", null, new { @class = "form-control phase-1" })
        @Html.ValidationMessageFor(m => m.GarageCars, "", new { @class = "text-danger" })


        <br />
        <label>Select o imagine</label>
        <input type="file" id="image1" name="image1" />
        <br />
        <!-- END BLOCK -->

        <button id="btn-confirmation" type="button" class="btn btn-primary btn-success"><span class="glyphicon glyphicon-pencil"></span> Confirmati Selectiile</button> 
        <button id="btn-edit" type="button" class="btn btn-primary btn-warning hide"><span class="glyphicon glyphicon-pencil"></span> Editati Selectiile</button> 
    </div>
    <!-- BEGIN Al doilea block de selectii -->
    <div id="#div-phase-2" class="col-md-4">
        <br />
        @Html.Label("SuggestedPrice", "Pret Sugerat:")
        <br />
        @Html.TextBox("SuggestedPrice", null, new { @class = "form-control", @readonly="readonly" })
        @Html.ValidationMessageFor(m => m.SuggestedPrice, "", new { @class = "text-danger" })
        <br />

        @Html.Label("Price", "Pret:")
        <br />
        @Html.TextBox("Price", null, new { @class = "form-control phase-2", Readonly = true })
        @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger"})
        <br />

        <button id="btn-add" type="submit" class="btn btn-primary btn-success phase-2" disabled><span class="glyphicon glyphicon-pencil"></span> Adauga anunt</button>
        <a class="btn btn-primary btn-danger" href="/House/Index"><span class="glyphicon glyphicon-remove"></span> Renunta</a>
    </div>
    <!-- END BLOCK -->
</div>

}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script src="../../Scripts/script-new.js"></script>

Web_Module/NOlx/Views/House/Show.cshtml
@model NOlx.Models.House
@{
    ViewBag.Title = @Model.Title;
}
@using NOlx.Controllers
<h3><b>@Model.Title </b></h3>
<div class="container">

    <div class="container bootstrap snippet">
        <div class="row ng-scope">
            @{ 
                var base64 = Convert.ToBase64String(@Model.Image);
                var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
            }
            
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <div class="pv-lg"><img class="center-block img-responsive img-circle img-thumbnail thumb96" src="@imgsrc" alt="Contact"></div>
                        
                        
                        <h4 class="m0 text-bold"> <i>Vandut de: </i><i class="glyphicon glyphicon-user"></i> @Utilss.GetUserName(Model.UserId)</h4>

                        <h3><b>Pret: </b> @Model.Price RON</h3>
                        
                        <br />
                        <br />
                        <div class="text-center"><a class="btn btn-primary" href="/House">Inapoi la anunturi</a></div>
                    </div>
                </div>
                
            </div>
            <div class="col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                       
                        <div class="h4 text-center">Informatii despre anunt</div>
                        <div class="row pv-lg">

                            <div class="col-lg-11">
                                <form class="form-horizontal ng-pristine ng-valid">


                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Descriere: </label>
                                        <div style="padding: 15px;" class="col-sm-8 jumbotron">
                                            @Model.Description
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Adresa: </label>
                                        <div  style="padding: 15px;" class="col-sm-8 jumbotron">
                                            @Model.Address
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label">Calitatea finisajelor: </label>
                                        <div style="padding: 15px;"  class="col-sm-8 jumbotron">
                                            @Utilss.GetOverallQual(Model.OverallQual)
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" >Interval estimat NOlx: </label>
                                        <div style="padding: 15px;"  class="col-sm-8 jumbotron">
                                             @{ 
                                                 var minInterval = Model.SuggestedPrice - Model.SuggestedPrice * 15 /100;
                                                 var maxInterval = Model.SuggestedPrice + Model.SuggestedPrice * 15 /100;
                                                 minInterval -= minInterval % 1000;
                                                 maxInterval -= maxInterval % 1000;
                                             }
                                            @minInterval - @maxInterval RON

                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" >Tipul de locuință : </label>
                                        <div  style="padding: 15px;" class="col-sm-8 jumbotron">
                                            @Utilss.GetMsSubClass(Model.MSSubClass)
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" >Numar bai: </label>
                                        <div style="padding: 15px;"  class="col-sm-8 jumbotron">
                                             @Model.FullBath
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" >An constructie: </label>
                                        <div style="padding: 15px;"  class="col-sm-8 jumbotron">
                                             @Model.YearBuilt
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" >Numar camere: </label>
                                        <div  style="padding: 15px;" class="col-sm-8 jumbotron">
                                             @Model.TotRmsAbvGrd
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" >Nivel echipare bucatarii: </label>
                                        <div  style="padding: 15px;" class="col-sm-8 jumbotron">
                                            @Utilss.KitchenQual(Model.KitchenQual)
                                        </div>
                                    </div>


                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>